close all;
files = {
        %'img_evaltests/dataset5/segment_cropped (23).png', ...
        %'img_evaltests/dataset5/segment_cropped (22).png', ...
        'img_evaltests/dataset5/segment_cropped (21).png', ...
        'img_evaltests/dataset5/segment_cropped (20).png', ...
        'img_evaltests/dataset5/segment_cropped (19).png', ...
        'img_evaltests/dataset5/segment_cropped (18).png', ...
        'img_evaltests/dataset5/segment_cropped (17).png', ...
        'img_evaltests/dataset5/segment_cropped (16).png', ...
        'img_evaltests/dataset5/segment_cropped (15).png', ...
        'img_evaltests/dataset5/segment_cropped (14).png', ...
        'img_evaltests/dataset5/segment_cropped (13).png', ...
        'img_evaltests/dataset5/segment_cropped (12).png', ...
        'img_evaltests/dataset5/segment_cropped (11).png', ...
        'img_evaltests/dataset5/segment_cropped (10).png', ...
        'img_evaltests/dataset5/segment_cropped (9).png', ...
        'img_evaltests/dataset5/segment_cropped (8).png', ...
        'img_evaltests/dataset5/segment_cropped (7).png', ...
        'img_evaltests/dataset5/segment_cropped (6).png', ...
        'img_evaltests/dataset5/segment_cropped (5).png', ...
        'img_evaltests/dataset5/segment_cropped (4).png', ...
        'img_evaltests/dataset5/segment_cropped (3).png', ...
        'img_evaltests/dataset5/segment_cropped (2).png', ...
        'img_evaltests/dataset5/segment_cropped (1).png', ...
         }; 

% files = {
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         'img_evaltests/dataset5/linetest.png', ...
%         };

path = cell2mat(files(15)); 
img = imread(path); 
images{1} = img;
%expTimes(i) = mean(img(:)); 
%expTimes{i} = img;
expTimes{1}=zeros(size(img));
    window = [10 10];
    expTimes{1}= movmean(img,window);
  expNormalized{1} = expTimes{1}./expTimes{1}(1);

subplot(3,1,1),imshow(images{1});
subplot(3,1,2),imshow(expNormalized{1});
subplot(3,1,3),imshow(double(images{1}) ./ expNormalized{1},[]);