close all;
files = {
        %'img_evaltests/dataset5/segment_cropped (23).png', ...
        %'img_evaltests/dataset5/segment_cropped (22).png', ...
        'img_evaltests/dataset5/hdr_global.png', ...
        'img_evaltests/dataset5/segment_cropped (21).png', ...
        'img_evaltests/dataset5/segment_cropped (20).png', ...
        'img_evaltests/dataset5/segment_cropped (19).png', ...
        'img_evaltests/dataset5/segment_cropped (18).png', ...
        'img_evaltests/dataset5/segment_cropped (17).png', ...
        'img_evaltests/dataset5/segment_cropped (16).png', ...
        'img_evaltests/dataset5/segment_cropped (15).png', ...
        'img_evaltests/dataset5/segment_cropped (14).png', ...
        'img_evaltests/dataset5/segment_cropped (13).png', ...
        'img_evaltests/dataset5/segment_cropped (12).png', ...
        'img_evaltests/dataset5/segment_cropped (11).png', ...
        'img_evaltests/dataset5/segment_cropped (10).png', ...
        'img_evaltests/dataset5/segment_cropped (9).png', ...
        'img_evaltests/dataset5/segment_cropped (8).png', ...
        'img_evaltests/dataset5/segment_cropped (7).png', ...
        'img_evaltests/dataset5/segment_cropped (6).png', ...
        'img_evaltests/dataset5/segment_cropped (5).png', ...
        'img_evaltests/dataset5/segment_cropped (4).png', ...
        'img_evaltests/dataset5/segment_cropped (3).png', ...
        'img_evaltests/dataset5/segment_cropped (2).png', ...
        'img_evaltests/dataset5/segment_cropped (1).png', ...
         }; 

figure;
path = files{1};
img = imread(path);
img = img(:,:,1);
out = isoutlier(double(img),'movmean',[10 200],'ThresholdFactor',1);
subplot(2,1,1),imshow(img);
subplot(2,1,2),imshow(out,[]);

figure;
path = files{2};
img = imread(path);
img = img(:,:,1);
out = isoutlier(double(img),'movmean',[10 200],'ThresholdFactor',1);
subplot(2,1,1),imshow(img);
subplot(2,1,2),imshow(out,[]);
